import type { CatalogPlugin } from './types';

export const GROUPS: Record<string, string> = {
  model: 'Модель и LLM',
  core: 'Ядро (spine)',
  fs: 'Файловая система',
  shell: 'Shell и терминал',
  web: 'Web',
  skill: 'Skills',
  subagent: 'Субагенты',
  workflow: 'Workflow',
  goal: 'Цели и задачи',
  compaction: 'Компакция и контекст',
  permission: 'Разрешения и политика',
  session: 'Сессии и хранение',
  command: 'Команды',
  telemetry: 'Телеметрия',
};

export const CATALOG: CatalogPlugin[] = [
  // ── model ────────────────────────────────────────────────
  {
    id: 'llm',
    name: '@deepseek-ai/dsh-llm',
    group: 'model',
    summary: 'LLM vocabulary и реестр адаптеров (ctx.llm).',
    role: 'core',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'llm-deepseek',
    name: '@deepseek-ai/dsh-llm-deepseek',
    group: 'model',
    summary: 'Адаптер DeepSeek: chat / reasoner / search endpoints.',
    role: 'core',
    fields: [
      { key: 'baseUrl', label: 'baseUrl', kind: 'string', hint: 'Базовый URL API' },
      { key: 'apiKeyEnv', label: 'apiKeyEnv', kind: 'string', hint: 'Имя env-переменной с ключом' },
      { key: 'models', label: 'models', kind: 'stringlist', hint: 'Список моделей по одному в строке' },
    ],
    defaults: { baseUrl: 'https://api.deepseek.com', apiKeyEnv: 'DEEPSEEK_API_KEY', models: ['deepseek-chat', 'deepseek-reasoner'] },
    enabled: true,
  },
  {
    id: 'llm-pi-ai',
    name: '@deepseek-ai/dsh-llm-pi-ai',
    group: 'model',
    summary: 'Мультипровайдерный адаптер. По умолчанию dormant (нет маршрутов).',
    role: 'core',
    fields: [],
    defaults: {},
    enabled: false,
  },
  {
    id: 'agent-default-model',
    name: '@deepseek-ai/dsh-agent-default-model',
    group: 'model',
    summary: 'Модель по умолчанию для новых агентов.',
    role: 'capability',
    fields: [
      { key: 'provider', label: 'provider', kind: 'select', options: ['deepseek-official', 'pi-ai'] },
      { key: 'model', label: 'model', kind: 'string', hint: 'Идентификатор модели' },
    ],
    defaults: { provider: 'deepseek-official', model: 'deepseek-v4-flash' },
    enabled: true,
  },
  {
    id: 'llm-retry',
    name: '@deepseek-ai/dsh-llm-retry',
    group: 'model',
    summary: 'Политика повторов запросов к модели.',
    role: 'policy',
    fields: [
      { key: 'maxRetries', label: 'maxRetries', kind: 'number' },
      { key: 'backoffMs', label: 'backoffMs', kind: 'number' },
    ],
    defaults: { maxRetries: 3, backoffMs: 500 },
    enabled: true,
  },

  // ── core ─────────────────────────────────────────────────
  {
    id: 'session',
    name: '@deepseek-ai/dsh-session',
    group: 'core',
    summary: 'Append-only SessionEvent лог и in-memory store (ctx.sessions).',
    role: 'core',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'system-prompt',
    name: '@deepseek-ai/dsh-system-prompt',
    group: 'core',
    summary: 'Сборка секций system prompt и tool schemas (ctx.systemPrompt).',
    role: 'core',
    fields: [
      { key: 'persona', label: 'persona', kind: 'multiline', hint: 'Персона агента. Поддерживает {{model}} и {{cwd}}' },
    ],
    defaults: { persona: 'You are a coding agent powered by the {{model}} model. Your working directory is {{cwd}}.' },
    enabled: true,
  },
  {
    id: 'tools',
    name: '@deepseek-ai/dsh-tools',
    group: 'core',
    summary: 'Scoped tool registry и guarded execution pipeline (ctx.tools).',
    role: 'core',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'agent',
    name: '@deepseek-ai/dsh-agent',
    group: 'core',
    summary: 'Интерфейс Agent, live registry и agent/* events (ctx.agents).',
    role: 'core',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'agent-loop',
    name: '@deepseek-ai/dsh-agent-loop',
    group: 'core',
    summary: 'Дефолтный driver: step = один запрос + вызванные tools.',
    role: 'core',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'typert-registry',
    name: '@deepseek-ai/dsh-typert-registry',
    group: 'core',
    summary: 'Runtime type registry (ctx.typert).',
    role: 'core',
    fields: [],
    defaults: {},
    enabled: true,
  },

  // ── fs ───────────────────────────────────────────────────
  {
    id: 'tool-fs',
    name: '@deepseek-ai/dsh-tool-fs',
    group: 'fs',
    summary: 'Модельный доступ к файловой системе (fs.read / fs.write / fs.edit).',
    role: 'tool',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'tool-fs-search',
    name: '@deepseek-ai/dsh-tool-fs-search',
    group: 'fs',
    summary: 'Поиск по файлам (glob + содержимое).',
    role: 'tool',
    fields: [
      { key: 'sampleOverCapGlobResults', label: 'sampleOverCapGlobResults', kind: 'boolean' },
    ],
    defaults: { sampleOverCapGlobResults: false },
    enabled: true,
  },
  {
    id: 'fs-observation-policy',
    name: '@deepseek-ai/dsh-fs-observation-policy',
    group: 'fs',
    summary: 'Политика наблюдения за файловыми эффектами.',
    role: 'policy',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'tool-str-replace-editor',
    name: '@deepseek-ai/dsh-tool-str-replace-editor',
    group: 'fs',
    summary: 'str_replace_editor — точные правки файлов.',
    role: 'tool',
    fields: [{ key: 'maxOutputChars', label: 'maxOutputChars', kind: 'number' }],
    defaults: { maxOutputChars: 16000 },
    enabled: true,
  },

  // ── shell ────────────────────────────────────────────────
  {
    id: 'tool-bash',
    name: '@deepseek-ai/dsh-tool-bash',
    group: 'shell',
    summary: 'Bash для модели (POSIX-хосты).',
    role: 'tool',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'tool-pwsh',
    name: '@deepseek-ai/dsh-tool-pwsh',
    group: 'shell',
    summary: 'PowerShell для модели (Windows-хосты).',
    role: 'tool',
    fields: [],
    defaults: {},
    enabled: false,
  },
  {
    id: 'bash-sandbox',
    name: '@deepseek-ai/dsh-bash-sandbox',
    group: 'shell',
    summary: 'Песочница bash-исполнения.',
    role: 'capability',
    fields: [{ key: 'timeoutMs', label: 'timeoutMs', kind: 'number' }],
    defaults: { timeoutMs: 60000 },
    enabled: true,
  },
  {
    id: 'pwsh-sandbox',
    name: '@deepseek-ai/dsh-pwsh-sandbox',
    group: 'shell',
    summary: 'Песочница PowerShell-исполнения.',
    role: 'capability',
    fields: [],
    defaults: {},
    enabled: false,
  },
  {
    id: 'shell-env',
    name: '@deepseek-ai/dsh-shell-env',
    group: 'shell',
    summary: 'Публикует DSH_WEB_URL / DSH_WEB_MODE в shell модели.',
    role: 'capability',
    fields: [],
    defaults: {},
    enabled: true,
  },

  // ── web ──────────────────────────────────────────────────
  {
    id: 'tool-web',
    name: '@deepseek-ai/dsh-tool-web',
    group: 'web',
    summary: 'Стабильный web_search для модели. fetch выключен (SSRF).',
    role: 'tool',
    fields: [],
    defaults: {},
    enabled: true,
  },

  // ── skill ────────────────────────────────────────────────
  {
    id: 'skill',
    name: '@deepseek-ai/dsh-skill',
    group: 'skill',
    summary: 'Реестр skill-провайдеров (ctx.skills).',
    role: 'core',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'skill-filesystem',
    name: '@deepseek-ai/dsh-skill-filesystem',
    group: 'skill',
    summary: 'Локальная загрузка skills с диска.',
    role: 'capability',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'tool-skill',
    name: '@deepseek-ai/dsh-tool-skill',
    group: 'skill',
    summary: 'Модельный доступ к каталогу и загрузчику skills.',
    role: 'tool',
    fields: [],
    defaults: {},
    enabled: true,
  },

  // ── subagent ─────────────────────────────────────────────
  {
    id: 'subagent',
    name: '@deepseek-ai/dsh-subagent',
    group: 'subagent',
    summary: 'Реестр субагентов и провайдеров делегирования.',
    role: 'core',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'tool-subagent',
    name: '@deepseek-ai/dsh-tool-subagent',
    group: 'subagent',
    summary: 'Инструмент делегирования субагенту (spawn).',
    role: 'tool',
    fields: [
      { key: 'provider', label: 'provider', kind: 'select', options: ['spawn', 'fork'] },
      { key: 'backgroundMode', label: 'backgroundMode', kind: 'select', options: ['one-shot', 'continuable'] },
    ],
    defaults: { provider: 'spawn', backgroundMode: 'continuable', toolName: 'subagent' },
    enabled: true,
  },
  {
    id: 'tool-subagent-fork',
    name: '@deepseek-ai/dsh-tool-subagent (fork)',
    group: 'subagent',
    summary: 'Делегирование через fork (наследует историю).',
    role: 'tool',
    fields: [
      { key: 'provider', label: 'provider', kind: 'select', options: ['spawn', 'fork'] },
      { key: 'backgroundMode', label: 'backgroundMode', kind: 'select', options: ['one-shot', 'continuable'] },
    ],
    defaults: { provider: 'fork', backgroundMode: 'one-shot', toolName: 'subagent_fork' },
    enabled: false,
  },
  {
    id: 'tool-subagent-control',
    name: '@deepseek-ai/dsh-tool-subagent-control',
    group: 'subagent',
    summary: 'Управление фоновыми субагентами + send_message.',
    role: 'tool',
    fields: [],
    defaults: {},
    enabled: true,
  },

  // ── workflow ─────────────────────────────────────────────
  {
    id: 'workflow-worker-thread',
    name: '@deepseek-ai/dsh-workflow-worker-thread',
    group: 'workflow',
    summary: 'Durable workflow в worker-треде.',
    role: 'capability',
    fields: [{ key: 'provider', label: 'provider', kind: 'string' }],
    defaults: { provider: 'spawn' },
    enabled: true,
  },
  {
    id: 'tool-workflow',
    name: '@deepseek-ai/dsh-tool-workflow',
    group: 'workflow',
    summary: 'Модельный инструмент workflow.',
    role: 'tool',
    fields: [],
    defaults: {},
    enabled: true,
  },

  // ── goal ─────────────────────────────────────────────────
  {
    id: 'goal',
    name: '@deepseek-ai/dsh-goal',
    group: 'goal',
    summary: 'Сервис целей (ctx.goals).',
    role: 'core',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'tool-goal',
    name: '@deepseek-ai/dsh-tool-goal',
    group: 'goal',
    summary: 'Модельный инструмент целей.',
    role: 'tool',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'tool-todo',
    name: '@deepseek-ai/dsh-tool-todo',
    group: 'goal',
    summary: 'todo_write — трекинг задач реализации.',
    role: 'tool',
    fields: [{ key: 'allowParallelInProgress', label: 'allowParallelInProgress', kind: 'boolean' }],
    defaults: { allowParallelInProgress: true },
    enabled: true,
  },

  // ── compaction ───────────────────────────────────────────
  {
    id: 'compaction-basic',
    name: '@deepseek-ai/dsh-compaction-basic',
    group: 'compaction',
    summary: 'Базовая компакция контекста.',
    role: 'capability',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'token-meter',
    name: '@deepseek-ai/dsh-token-meter',
    group: 'compaction',
    summary: 'Измерение токенов для контекста.',
    role: 'capability',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'tool-result-pruner',
    name: '@deepseek-ai/dsh-compaction-tool-result-pruner',
    group: 'compaction',
    summary: 'Обрезка больших tool-результатов до бюджета.',
    role: 'policy',
    fields: [
      { key: 'thresholdChars', label: 'thresholdChars', kind: 'number' },
      { key: 'headChars', label: 'headChars', kind: 'number' },
      { key: 'tailChars', label: 'tailChars', kind: 'number' },
    ],
    defaults: { thresholdChars: 8192, headChars: 4096, tailChars: 1024 },
    enabled: true,
  },

  // ── permission ───────────────────────────────────────────
  {
    id: 'sandbox',
    name: '@deepseek-ai/dsh-sandbox-local',
    group: 'permission',
    summary: 'Локальная песочница (file-effect boundary).',
    role: 'capability',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'sandbox-policy',
    name: '@deepseek-ai/dsh-sandbox-policy',
    group: 'permission',
    summary: 'Режим доступа к файловой системе.',
    role: 'policy',
    fields: [
      { key: 'mode', label: 'mode', kind: 'select', options: ['read-only', 'workspace-write', 'danger-full-access'] },
      { key: 'workspaceRoot', label: 'workspaceRoot', kind: 'string', hint: 'Корень workspace' },
    ],
    defaults: { mode: 'workspace-write', workspaceRoot: '.' },
    enabled: true,
  },
  {
    id: 'approval',
    name: '@deepseek-ai/dsh-user-approval',
    group: 'permission',
    summary: 'Политика подтверждения действий (ask / never).',
    role: 'policy',
    fields: [
      { key: 'policy', label: 'policy', kind: 'select', options: ['ask', 'never'] },
    ],
    defaults: { policy: 'ask' },
    enabled: true,
  },
  {
    id: 'permission',
    name: '@deepseek-ai/dsh-permission-presets',
    group: 'permission',
    summary: 'Готовые пресеты разрешений.',
    role: 'policy',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'timeout-policy',
    name: '@deepseek-ai/dsh-tool-call-timeout-policy',
    group: 'permission',
    summary: 'Таймауты tool-вызовов.',
    role: 'policy',
    fields: [],
    defaults: {},
    enabled: true,
  },

  // ── session ──────────────────────────────────────────────
  {
    id: 'session-persistence-jsonl',
    name: '@deepseek-ai/dsh-session-persistence-jsonl',
    group: 'session',
    summary: 'Durable persistence сессий (JSONL).',
    role: 'storage',
    fields: [{ key: 'root', label: 'root', kind: 'string', hint: 'Директория session-логов' }],
    defaults: { root: '~/.dsh/sessions' },
    enabled: true,
  },
  {
    id: 'session-persistence-sqlite',
    name: '@deepseek-ai/dsh-session-persistence-sqlite',
    group: 'session',
    summary: 'Persistence сессий (SQLite).',
    role: 'storage',
    fields: [],
    defaults: {},
    enabled: false,
  },
  {
    id: 'session-query-sqlite',
    name: '@deepseek-ai/dsh-session-query-sqlite',
    group: 'session',
    summary: 'Чтение/поиск сессий; openAt=never — без full-text.',
    role: 'storage',
    fields: [
      { key: 'path', label: 'path', kind: 'string' },
      { key: 'openAt', label: 'openAt', kind: 'select', options: ['never', 'first-search', 'startup'] },
    ],
    defaults: { path: ':memory:', openAt: 'never' },
    enabled: true,
  },
  {
    id: 'session-title',
    name: '@deepseek-ai/dsh-session-title',
    group: 'session',
    summary: 'Генерация заголовков сессий из лога.',
    role: 'capability',
    fields: [
      { key: 'fallbackMaxWords', label: 'fallbackMaxWords', kind: 'number' },
      { key: 'maxTitleBytes', label: 'maxTitleBytes', kind: 'number' },
    ],
    defaults: { fallbackMaxWords: 5, fallbackMaxBytes: 40, maxTitleBytes: 80 },
    enabled: true,
  },
  {
    id: 'session-checkpoint-policy',
    name: '@deepseek-ai/dsh-session-checkpoint-policy',
    group: 'session',
    summary: 'Чекпоинты durable перед каждым запросом.',
    role: 'policy',
    fields: [],
    defaults: {},
    enabled: true,
  },

  // ── command ──────────────────────────────────────────────
  {
    id: 'commands',
    name: '@deepseek-ai/dsh-commands',
    group: 'command',
    summary: 'Реестр человеческих команд (ctx.commands).',
    role: 'core',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'command-compact',
    name: '@deepseek-ai/dsh-command-compact',
    group: 'command',
    summary: 'Команда /compact.',
    role: 'capability',
    fields: [],
    defaults: {},
    enabled: true,
  },
  {
    id: 'command-goal',
    name: '@deepseek-ai/dsh-command-goal',
    group: 'command',
    summary: 'Команда /goal.',
    role: 'capability',
    fields: [],
    defaults: {},
    enabled: true,
  },

  // ── telemetry ────────────────────────────────────────────
  {
    id: 'session-telemetry-otel',
    name: '@deepseek-ai/dsh-session-telemetry-otel',
    group: 'telemetry',
    summary: 'OTLP-телеметрия. По умолчанию DISABLED.',
    role: 'policy',
    fields: [
      { key: 'mode', label: 'mode', kind: 'select', options: ['DISABLED', 'FEEDBACK_ONLY', 'FULL'] },
      { key: 'url', label: 'exporter.url', kind: 'string' },
    ],
    defaults: { mode: 'DISABLED' },
    enabled: false,
  },
];

export const byId = new Map(CATALOG.map((p) => [p.id, p]));

export const groupOrder = [
  'model',
  'core',
  'fs',
  'shell',
  'web',
  'skill',
  'subagent',
  'workflow',
  'goal',
  'compaction',
  'permission',
  'session',
  'command',
  'telemetry',
];