import type { CatalogPlugin } from './types'

export const CATALOG: CatalogPlugin[] = [
  // ── Модель и LLM ──
  {
    id: 'llm',
    npmName: '@deepseek-ai/dsh-llm',
    label: 'LLM Service',
    group: 'Модель и LLM',
    summary: 'LLM capability service definition',
    role: 'core',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'llm-deepseek',
    npmName: '@deepseek-ai/dsh-llm-deepseek',
    label: 'LLM: DeepSeek',
    group: 'Модель и LLM',
    summary: 'DeepSeek API adapter (gpt-4o-mini by default)',
    role: 'core',
    plane: 'host',
    fields: [
      { key: 'apiKeyEnv', label: 'API Key Env', kind: 'string', hint: 'Environment variable name for the API key' },
      { key: 'baseURL', label: 'Base URL', kind: 'string', hint: 'API endpoint URL' },
      { key: 'thinking', label: 'Thinking', kind: 'select', options: ['enabled', 'disabled'], hint: 'Enable extended thinking' },
      { key: 'reasoningEffort', label: 'Reasoning Effort', kind: 'select', options: ['off', 'high', 'max'], hint: 'Reasoning effort level' },
      { key: 'maxTokens', label: 'Max Tokens', kind: 'number', min: 1, max: 1000000, hint: 'Max output tokens per response' },
      { key: 'defaultContextWindow', label: 'Context Window', kind: 'number', min: 1000, max: 10000000, hint: 'Default context window size' },
      { key: 'models', label: 'Models', kind: 'stringlist', hint: 'Model IDs (one per line)' },
      { key: 'streamIdleTimeoutMs', label: 'Stream Idle Timeout (ms)', kind: 'number', min: 0, max: 3600000, hint: 'Idle timeout before stream closes' },
    ],
    defaults: { apiKeyEnv: 'DEEPSEEK_API_KEY', maxTokens: 256000, defaultContextWindow: 1000000, models: ['gpt-4o-mini'] },
  },
  {
    id: 'llm-retry',
    npmName: '@deepseek-ai/dsh-llm-retry',
    label: 'LLM Retry Policy',
    group: 'Модель и LLM',
    summary: 'Retry failed LLM requests with backoff',
    role: 'core',
    plane: 'host',
    fields: [
      { key: 'maxRetries', label: 'Max Retries', kind: 'number', min: 0, max: 10, hint: 'Maximum retry attempts' },
      { key: 'baseDelayMs', label: 'Base Delay (ms)', kind: 'number', min: 100, max: 60000, hint: 'Base delay between retries' },
    ],
    defaults: { maxRetries: 3, baseDelayMs: 1000 },
  },
  {
    id: 'agent-default-model',
    npmName: '@deepseek-ai/dsh-agent-default-model',
    label: 'Default Model',
    group: 'Модель и LLM',
    summary: 'Default provider and model for new sessions',
    role: 'core',
    plane: 'host',
    fields: [
      { key: 'provider', label: 'Provider', kind: 'string', hint: 'LLM provider id' },
      { key: 'model', label: 'Model', kind: 'string', hint: 'Model identifier' },
    ],
    defaults: { provider: 'deepseek-official', model: 'gpt-4o-mini' },
  },

  // ── Ядро spine ──
  {
    id: 'agent',
    npmName: '@deepseek-ai/dsh-agent',
    label: 'Agent',
    group: 'Ядро spine',
    summary: 'Agent interface and lifecycle',
    role: 'core',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'agent-loop',
    npmName: '@deepseek-ai/dsh-agent-loop',
    label: 'Agent Loop',
    group: 'Ядро spine',
    summary: 'Main agent execution loop',
    role: 'core',
    plane: 'host',
    fields: [
      { key: 'maxParallelToolCalls', label: 'Max Parallel Tool Calls', kind: 'number', min: 1, max: 20, hint: 'Max concurrent tool calls' },
    ],
    defaults: { maxParallelToolCalls: 4 },
  },
  {
    id: 'agent-instructions',
    npmName: '@deepseek-ai/dsh-agent-instructions',
    label: 'Agent Instructions',
    group: 'Ядро spine',
    summary: 'Workspace instruction loader (AGENTS.md, etc.)',
    role: 'core',
    plane: 'host',
    fields: [
      { key: 'maxBytes', label: 'Max Bytes', kind: 'number', min: 1024, max: 1048576, hint: 'Max instruction bytes' },
      { key: 'maxSourceBytes', label: 'Max Source Bytes', kind: 'number', min: 1024, max: 1048576, hint: 'Max source file bytes to read' },
    ],
    defaults: { maxBytes: 65536 },
  },
  {
    id: 'system-prompt',
    npmName: '@deepseek-ai/dsh-system-prompt',
    label: 'System Prompt',
    group: 'Ядро spine',
    summary: 'Prompt section and tool schema assembly',
    role: 'core',
    plane: 'host',
    fields: [
      { key: 'persona', label: 'Persona', kind: 'multiline', hint: 'System persona text (deployment-specific)' },
    ],
    defaults: { persona: '' },
  },
  {
    id: 'tools',
    npmName: '@deepseek-ai/dsh-tools',
    label: 'Tools Registry',
    group: 'Ядро spine',
    summary: 'Tool registration and presentation',
    role: 'core',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'typert',
    npmName: '@deepseek-ai/dsh-typert',
    label: 'Type Graph',
    group: 'Ядро spine',
    summary: 'Type graph generator and registry',
    role: 'core',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'timer',
    npmName: 'cordis-plugin-timer',
    label: 'Timer',
    group: 'Ядро spine',
    summary: 'Cordis timer plugin',
    role: 'core',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'hmr',
    npmName: 'cordis-plugin-hmr',
    label: 'HMR',
    group: 'Ядро spine',
    summary: 'Hot module replacement',
    role: 'core',
    plane: 'host',
    fields: [
      { key: 'root', label: 'Root', kind: 'stringlist', hint: 'Watch roots' },
    ],
    defaults: { root: ['.'] },
  },

  // ── Файловая система ──
  {
    id: 'fs-local',
    npmName: '@deepseek-ai/dsh-fs-local',
    label: 'FS: Local',
    group: 'Файловая система',
    summary: 'Local filesystem provider',
    role: 'storage',
    plane: 'host',
    fields: [
      { key: 'cwd', label: 'CWD', kind: 'string', hint: 'Working directory' },
      { key: 'diffBasisMaxBytes', label: 'Diff Max Bytes', kind: 'number', min: 1024, max: 104857600, hint: 'Max file size for diff basis' },
    ],
    defaults: { diffBasisMaxBytes: 10485760 },
  },
  {
    id: 'fs-sandbox',
    npmName: '@deepseek-ai/dsh-fs-sandbox',
    label: 'FS: Sandbox',
    group: 'Файловая система',
    summary: 'Sandboxed filesystem with policy fencing',
    role: 'storage',
    plane: 'host',
    fields: [
      { key: 'cwd', label: 'CWD', kind: 'string', hint: 'Working directory' },
    ],
    defaults: {},
    dependencies: ['fs-local'],
  },
  {
    id: 'tool-fs',
    npmName: '@deepseek-ai/dsh-tool-fs',
    label: 'Tool: FS Read/Write/Edit',
    group: 'Файловая система',
    summary: 'Filesystem tools for agent (read, write, edit)',
    role: 'tool',
    plane: 'agent',
    fields: [
      { key: 'readLimit', label: 'Read Limit', kind: 'number', min: 100, max: 1000000, hint: 'Max bytes per read' },
      { key: 'readMaxLineLength', label: 'Max Line Length', kind: 'number', min: 100, max: 100000, hint: 'Max line length' },
      { key: 'readMaxBytes', label: 'Read Max Bytes', kind: 'number', min: 1024, max: 10485760, hint: 'Absolute max read bytes' },
    ],
    defaults: {},
    dependencies: ['fs-local', 'fs-sandbox'],
  },
  {
    id: 'tool-fs-search',
    npmName: '@deepseek-ai/dsh-tool-fs-search',
    label: 'Tool: FS Search (Glob/Grep)',
    group: 'Файловая система',
    summary: 'File search tools (glob, grep)',
    role: 'tool',
    plane: 'agent',
    fields: [
      { key: 'globMaxResults', label: 'Glob Max Results', kind: 'number', min: 10, max: 10000, hint: 'Max glob results' },
      { key: 'grepMaxMatches', label: 'Grep Max Matches', kind: 'number', min: 10, max: 1000, hint: 'Max grep matches' },
      { key: 'timeoutMs', label: 'Timeout (ms)', kind: 'number', min: 1000, max: 120000, hint: 'Search timeout' },
    ],
    defaults: { globMaxResults: 200, grepMaxMatches: 250, timeoutMs: 30000 },
    dependencies: ['fs-local', 'fs-sandbox'],
  },

  // ── Shell ──
  {
    id: 'subprocess',
    npmName: '@deepseek-ai/dsh-subprocess-local',
    label: 'Subprocess Manager',
    group: 'Shell',
    summary: 'Local subprocess management',
    role: 'core',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'bash-local',
    npmName: '@deepseek-ai/dsh-bash-local',
    label: 'Bash: Local',
    group: 'Shell',
    summary: 'Local bash executor',
    role: 'capability',
    plane: 'host',
    fields: [
      { key: 'cwd', label: 'CWD', kind: 'string', hint: 'Working directory' },
      { key: 'timeoutMs', label: 'Timeout (ms)', kind: 'number', min: 1000, max: 600000, hint: 'Default command timeout' },
      { key: 'maxTimeoutMs', label: 'Max Timeout (ms)', kind: 'number', min: 5000, max: 3600000, hint: 'Absolute max timeout' },
      { key: 'maxOutputBytes', label: 'Max Output Bytes', kind: 'number', min: 1024, max: 1048576, hint: 'Max stdout/stderr bytes' },
    ],
    defaults: { timeoutMs: 120000, maxTimeoutMs: 600000, maxOutputBytes: 64000 },
    dependencies: ['subprocess'],
  },
  {
    id: 'bash-sandbox',
    npmName: '@deepseek-ai/dsh-bash-sandbox',
    label: 'Bash: Sandbox',
    group: 'Shell',
    summary: 'Sandboxed bash executor',
    role: 'capability',
    plane: 'host',
    fields: [
      { key: 'timeoutMs', label: 'Timeout (ms)', kind: 'number', min: 1000, max: 600000 },
    ],
    defaults: { timeoutMs: 120000 },
    dependencies: ['subprocess', 'sandbox'],
  },
  {
    id: 'tool-bash',
    npmName: '@deepseek-ai/dsh-tool-bash',
    label: 'Tool: Bash',
    group: 'Shell',
    summary: 'Shell tool for agent (run commands)',
    role: 'tool',
    plane: 'agent',
    fields: [
      { key: 'enableRunInBackground', label: 'Run in Background', kind: 'boolean', hint: 'Allow background command execution' },
    ],
    defaults: { enableRunInBackground: true },
    dependencies: ['bash-local', 'bash-sandbox'],
  },

  // ── Web ──
  {
    id: 'web',
    npmName: '@deepseek-ai/dsh-web',
    label: 'Web Service',
    group: 'Web',
    summary: 'Web capability service (search + fetch)',
    role: 'core',
    plane: 'host',
    fields: [
      { key: 'searchProvider', label: 'Search Provider', kind: 'string', hint: 'Search provider id' },
      { key: 'fetchProvider', label: 'Fetch Provider', kind: 'string', hint: 'Fetch provider id' },
    ],
    defaults: {},
  },
  {
    id: 'web-search-deepseek',
    npmName: '@deepseek-ai/dsh-web-search-deepseek',
    label: 'Web Search: DeepSeek',
    group: 'Web',
    summary: 'DeepSeek web search provider',
    role: 'capability',
    plane: 'host',
    fields: [
      { key: 'apiKeyEnv', label: 'API Key Env', kind: 'string' },
      { key: 'model', label: 'Model', kind: 'string', hint: 'Search model' },
      { key: 'maxTokens', label: 'Max Tokens', kind: 'number', min: 256, max: 32000 },
      { key: 'maxUses', label: 'Max Uses', kind: 'number', min: 1, max: 20 },
    ],
    defaults: { model: 'deepseek-v4-flash', maxTokens: 4096, maxUses: 5 },
    dependencies: ['web'],
  },
  {
    id: 'tool-web',
    npmName: '@deepseek-ai/dsh-tool-web',
    label: 'Tool: Web Search/Fetch',
    group: 'Web',
    summary: 'Web search and fetch tools for agent',
    role: 'tool',
    plane: 'agent',
    fields: [
      { key: 'search', label: 'Enable Search', kind: 'boolean' },
      { key: 'fetch', label: 'Enable Fetch', kind: 'boolean' },
      { key: 'searchMaxResults', label: 'Max Search Results', kind: 'number', min: 1, max: 20 },
      { key: 'fetchTimeoutMs', label: 'Fetch Timeout (ms)', kind: 'number', min: 5000, max: 120000 },
      { key: 'fetchMaxOutputChars', label: 'Fetch Max Chars', kind: 'number', min: 1000, max: 1000000 },
    ],
    defaults: { search: true, fetch: false, searchMaxResults: 5, fetchTimeoutMs: 30000, fetchMaxOutputChars: 200000 },
    dependencies: ['web', 'web-search-deepseek'],
  },

  // ── Skills ──
  {
    id: 'skill',
    npmName: '@deepseek-ai/dsh-skill',
    label: 'Skill Registry',
    group: 'Skills',
    summary: 'Skill provider registry and catalog merging',
    role: 'core',
    plane: 'host',
    fields: [
      { key: 'collectCacheMaxEntries', label: 'Cache Max Entries', kind: 'number', min: 1, max: 1024 },
    ],
    defaults: { collectCacheMaxEntries: 128 },
  },
  {
    id: 'skill-filesystem',
    npmName: '@deepseek-ai/dsh-skill-filesystem',
    label: 'Skill: Filesystem Discovery',
    group: 'Skills',
    summary: 'Discovers SKILL.md files from filesystem roots',
    role: 'capability',
    plane: 'host',
    fields: [
      { key: 'includeDefaultRoots', label: 'Include Default Roots', kind: 'boolean' },
      { key: 'customSkillDirs', label: 'Custom Skill Dirs', kind: 'stringlist', hint: 'Additional skill directories' },
      { key: 'watch', label: 'Watch for Changes', kind: 'boolean' },
    ],
    defaults: { includeDefaultRoots: true, watch: true },
    dependencies: ['skill'],
  },
  {
    id: 'tool-skill',
    npmName: '@deepseek-ai/dsh-tool-skill',
    label: 'Tool: Skill Loader',
    group: 'Skills',
    summary: 'Model-facing skill catalog and loader tool',
    role: 'tool',
    plane: 'agent',
    fields: [
      { key: 'catalogDescriptionMaxLength', label: 'Description Max Length', kind: 'number', min: 3, max: 5000 },
    ],
    defaults: { catalogDescriptionMaxLength: 500 },
    dependencies: ['skill', 'skill-filesystem'],
  },

  // ── Субагенты ──
  {
    id: 'subagent',
    npmName: '@deepseek-ai/dsh-subagent',
    label: 'Subagent Registry',
    group: 'Субагенты',
    summary: 'Subagent delegation registry',
    role: 'core',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'subagent-spawn',
    npmName: '@deepseek-ai/dsh-subagent-spawn-in-process',
    label: 'Subagent: Spawn Provider',
    group: 'Субагенты',
    summary: 'In-process subagent spawn provider',
    role: 'capability',
    plane: 'host',
    fields: [
      { key: 'providerName', label: 'Provider Name', kind: 'string' },
    ],
    defaults: { providerName: 'spawn' },
    dependencies: ['subagent'],
  },
  {
    id: 'subagent-fork',
    npmName: '@deepseek-ai/dsh-subagent-fork-in-process',
    label: 'Subagent: Fork Provider',
    group: 'Субагенты',
    summary: 'In-process subagent fork provider',
    role: 'capability',
    plane: 'host',
    fields: [
      { key: 'providerName', label: 'Provider Name', kind: 'string' },
    ],
    defaults: { providerName: 'fork' },
    dependencies: ['subagent'],
  },
  {
    id: 'tool-subagent',
    npmName: '@deepseek-ai/dsh-tool-subagent',
    label: 'Tool: Subagent Delegate',
    group: 'Субагенты',
    summary: 'Delegate tasks to subagents',
    role: 'tool',
    plane: 'agent',
    fields: [
      { key: 'provider', label: 'Provider', kind: 'select', options: ['spawn', 'fork'] },
      { key: 'enableRunInBackground', label: 'Background Mode', kind: 'boolean' },
      { key: 'backgroundMode', label: 'Background Type', kind: 'select', options: ['one-shot', 'continuable'] },
      { key: 'maxDepth', label: 'Max Depth', kind: 'number', min: 1, max: 10 },
      { key: 'persona', label: 'Subagent Persona', kind: 'multiline', hint: 'System prompt for subagents' },
    ],
    defaults: { provider: 'spawn', enableRunInBackground: true, backgroundMode: 'one-shot', maxDepth: 3 },
    dependencies: ['subagent', 'subagent-spawn', 'subagent-fork'],
  },

  // ── Workflow ──
  {
    id: 'workflow-worker',
    npmName: '@deepseek-ai/dsh-workflow-worker-thread',
    label: 'Workflow Engine',
    group: 'Workflow',
    summary: 'Worker-thread workflow execution engine',
    role: 'core',
    plane: 'host',
    fields: [
      { key: 'provider', label: 'Provider', kind: 'select', options: ['spawn', 'fork'] },
    ],
    defaults: { provider: 'spawn' },
  },
  {
    id: 'tool-workflow',
    npmName: '@deepseek-ai/dsh-tool-workflow',
    label: 'Tool: Workflow',
    group: 'Workflow',
    summary: 'Workflow orchestration tool for agent',
    role: 'tool',
    plane: 'agent',
    fields: [],
    defaults: {},
    dependencies: ['workflow-worker'],
  },
  {
    id: 'tool-ralph',
    npmName: '@deepseek-ai/dsh-tool-ralph',
    label: 'Tool: Ralph',
    group: 'Workflow',
    summary: 'Ralph iteration tool (multi-round agent)',
    role: 'tool',
    plane: 'agent',
    fields: [
      { key: 'subagentProvider', label: 'Subagent Provider', kind: 'select', options: ['spawn', 'fork'] },
      { key: 'maxRounds', label: 'Max Rounds', kind: 'number', min: 1, max: 256 },
    ],
    defaults: { subagentProvider: 'spawn', maxRounds: 64 },
    dependencies: ['subagent', 'subagent-spawn'],
  },

  // ── Цели ──
  {
    id: 'goal',
    npmName: '@deepseek-ai/dsh-goal',
    label: 'Goal System',
    group: 'Цели',
    summary: 'Goal tracking and lifecycle',
    role: 'core',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'tool-goal',
    npmName: '@deepseek-ai/dsh-tool-goal',
    label: 'Tool: Goal',
    group: 'Цели',
    summary: 'Goal creation and tracking tool for agent',
    role: 'tool',
    plane: 'agent',
    fields: [],
    defaults: {},
    dependencies: ['goal'],
  },
  {
    id: 'tool-todo',
    npmName: '@deepseek-ai/dsh-tool-todo',
    label: 'Tool: Todo',
    group: 'Цели',
    summary: 'Todo list management tool',
    role: 'tool',
    plane: 'agent',
    fields: [
      { key: 'allowParallelInProgress', label: 'Allow Parallel Tasks', kind: 'boolean', hint: 'Allow multiple in-progress todos' },
    ],
    defaults: { allowParallelInProgress: true },
  },

  // ── Компакция ──
  {
    id: 'token-meter',
    npmName: '@deepseek-ai/dsh-token-meter',
    label: 'Token Meter',
    group: 'Компакция',
    summary: 'Token usage tracking',
    role: 'core',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'compaction-basic',
    npmName: '@deepseek-ai/dsh-compaction-basic',
    label: 'Compaction: Basic',
    group: 'Компакция',
    summary: 'Automatic context compaction when nearing limit',
    role: 'capability',
    plane: 'agent',
    fields: [
      { key: 'thresholdRatio', label: 'Threshold Ratio', kind: 'number', min: 0.1, max: 1.0, hint: 'Fraction of context window to trigger compaction' },
      { key: 'retainRatio', label: 'Retain Ratio', kind: 'number', min: 0.01, max: 0.5, hint: 'Fraction of context to retain' },
      { key: 'maxTokens', label: 'Max Tokens', kind: 'number', min: 1024, max: 100000, hint: 'Max output tokens for compaction' },
      { key: 'compactionRetries', label: 'Retries', kind: 'number', min: 0, max: 5 },
      { key: 'auto', label: 'Auto Compact', kind: 'boolean', hint: 'Automatically compact when threshold reached' },
    ],
    defaults: { thresholdRatio: 0.8, retainRatio: 0.16, maxTokens: 8192, compactionRetries: 1, auto: true },
    dependencies: ['llm'],
  },
  {
    id: 'tool-result-pruner',
    npmName: '@deepseek-ai/dsh-compaction-tool-result-pruner',
    label: 'Tool Result Pruner',
    group: 'Компакция',
    summary: 'Prune large tool results to save context',
    role: 'capability',
    plane: 'agent',
    fields: [
      { key: 'thresholdChars', label: 'Threshold (chars)', kind: 'number', min: 512, max: 100000, hint: 'Prune results larger than this' },
      { key: 'headChars', label: 'Head (chars)', kind: 'number', min: 128, max: 50000, hint: 'Characters to keep from start' },
      { key: 'tailChars', label: 'Tail (chars)', kind: 'number', min: 128, max: 50000, hint: 'Characters to keep from end' },
    ],
    defaults: { thresholdChars: 8192, headChars: 4096, tailChars: 1024 },
  },
  {
    id: 'command-compact',
    npmName: '@deepseek-ai/dsh-command-compact',
    label: 'Command: /compact',
    group: 'Компакция',
    summary: 'Manual /compact command for agent',
    role: 'capability',
    plane: 'agent',
    fields: [],
    defaults: {},
    dependencies: ['compaction-basic'],
  },

  // ── Разрешения ──
  {
    id: 'sandbox',
    npmName: '@deepseek-ai/dsh-sandbox-local',
    label: 'Sandbox Provider',
    group: 'Разрешения',
    summary: 'Local sandbox for code execution',
    role: 'policy',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'sandbox-policy',
    npmName: '@deepseek-ai/dsh-sandbox-policy',
    label: 'Sandbox Policy',
    group: 'Разрешения',
    summary: 'Filesystem write permissions for sandbox',
    role: 'policy',
    plane: 'host',
    fields: [
      { key: 'mode', label: 'Mode', kind: 'select', options: ['read-only', 'workspace-write', 'danger-full-access'], hint: 'Filesystem access level' },
      { key: 'workspaceRoot', label: 'Workspace Root', kind: 'string', hint: 'Root directory for workspace-write mode' },
    ],
    defaults: { mode: 'workspace-write' },
    dependencies: ['sandbox'],
  },
  {
    id: 'approval',
    npmName: '@deepseek-ai/dsh-user-approval',
    label: 'User Approval',
    group: 'Разрешения',
    summary: 'User approval policy for dangerous actions',
    role: 'policy',
    plane: 'host',
    fields: [
      { key: 'policy', label: 'Policy', kind: 'select', options: ['ask', 'never'], hint: 'When to ask user for approval' },
    ],
    defaults: { policy: 'ask' },
  },
  {
    id: 'permission-presets',
    npmName: '@deepseek-ai/dsh-permission-presets',
    label: 'Permission Presets',
    group: 'Разрешения',
    summary: 'Predefined permission profiles',
    role: 'policy',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'repeat-tool-reminder',
    npmName: '@deepseek-ai/dsh-repeat-tool-reminder',
    label: 'Repeat Tool Guard',
    group: 'Разрешения',
    summary: 'Detects repeated tool calls and reminds agent',
    role: 'policy',
    plane: 'agent',
    fields: [
      { key: 'thresholds', label: 'Thresholds', kind: 'stringlist', hint: 'Repeat count thresholds' },
      { key: 'argumentsPreviewChars', label: 'Preview Chars', kind: 'number', min: 100, max: 2000 },
    ],
    defaults: { thresholds: ['3', '5', '8'], argumentsPreviewChars: 500 },
  },
  {
    id: 'timeout-policy',
    npmName: '@deepseek-ai/dsh-tool-call-timeout-policy',
    label: 'Timeout Policy',
    group: 'Разрешения',
    summary: 'Cooperative tool-call timeout enforcement',
    role: 'policy',
    plane: 'agent',
    fields: [],
    defaults: {},
  },
  {
    id: 'fs-observation',
    npmName: '@deepseek-ai/dsh-fs-observation-policy',
    label: 'FS Observation Policy',
    group: 'Разрешения',
    summary: 'Read-before-edit enforcement',
    role: 'policy',
    plane: 'host',
    fields: [],
    defaults: {},
  },

  // ── Сессии ──
  {
    id: 'session',
    npmName: '@deepseek-ai/dsh-session',
    label: 'Session Manager',
    group: 'Сессии',
    summary: 'Session event log and lifecycle',
    role: 'core',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'session-persistence',
    npmName: '@deepseek-ai/dsh-session-persistence-jsonl',
    label: 'Session: JSONL Persistence',
    group: 'Сессии',
    summary: 'JSONL-based session persistence',
    role: 'storage',
    plane: 'host',
    fields: [
      { key: 'root', label: 'Root Dir', kind: 'string', hint: 'Session storage directory' },
    ],
    defaults: {},
    dependencies: ['session'],
  },
  {
    id: 'session-title',
    npmName: '@deepseek-ai/dsh-session-title',
    label: 'Session: Auto Title',
    group: 'Сессии',
    summary: 'Auto-generate session titles',
    role: 'capability',
    plane: 'host',
    fields: [
      { key: 'fallbackMaxWords', label: 'Fallback Max Words', kind: 'number', min: 1, max: 20 },
      { key: 'maxTitleBytes', label: 'Max Title Bytes', kind: 'number', min: 20, max: 200 },
    ],
    defaults: { fallbackMaxWords: 5, maxTitleBytes: 80 },
    dependencies: ['session'],
  },
  {
    id: 'session-telemetry',
    npmName: '@deepseek-ai/dsh-session-telemetry-otel',
    label: 'Session: Telemetry (OTEL)',
    group: 'Сессии',
    summary: 'OpenTelemetry session telemetry',
    role: 'capability',
    plane: 'host',
    fields: [
      { key: 'mode', label: 'Mode', kind: 'select', options: ['DISABLED', 'ENABLED'], hint: 'Telemetry collection mode' },
      { key: 'exporter.url', label: 'Exporter URL', kind: 'string', hint: 'OTLP endpoint URL' },
    ],
    defaults: { mode: 'DISABLED' },
    dependencies: ['session'],
  },

  // ── Команды ──
  {
    id: 'commands',
    npmName: '@deepseek-ai/dsh-commands',
    label: 'Commands Registry',
    group: 'Команды',
    summary: 'Slash command registry',
    role: 'core',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'plan-mode',
    npmName: '@deepseek-ai/dsh-plan-mode',
    label: 'Plan Mode',
    group: 'Команды',
    summary: 'Agent plan mode with structured reasoning',
    role: 'capability',
    plane: 'agent',
    fields: [
      { key: 'section', label: 'Instructions', kind: 'multiline', hint: 'Plan mode system prompt section' },
    ],
    defaults: {},
  },

  // ── Телеметрия ──
  {
    id: 'spill',
    npmName: '@deepseek-ai/dsh-spill-local',
    label: 'Spill Manager',
    group: 'Телеметрия',
    summary: 'Output spill management for large tool results',
    role: 'storage',
    plane: 'host',
    fields: [
      { key: 'maxInlineBytes', label: 'Max Inline Bytes', kind: 'number', min: 1000, max: 1000000 },
    ],
    defaults: { maxInlineBytes: 50000 },
  },
  {
    id: 'spill-policy',
    npmName: '@deepseek-ai/dsh-spill-policy',
    label: 'Spill Policy',
    group: 'Телеметрия',
    summary: 'When and how to spill large outputs to disk',
    role: 'policy',
    plane: 'host',
    fields: [],
    defaults: {},
    dependencies: ['spill'],
  },
  {
    id: 'attachment',
    npmName: '@deepseek-ai/dsh-attachment-local',
    label: 'Attachment Storage',
    group: 'Телеметрия',
    summary: 'Local image attachment storage',
    role: 'storage',
    plane: 'host',
    fields: [],
    defaults: {},
  },
  {
    id: 'shell-env',
    npmName: '@deepseek-ai/dsh-shell-env',
    label: 'Shell Environment',
    group: 'Телеметрия',
    summary: 'DSH environment variables',
    role: 'core',
    plane: 'host',
    fields: [],
    defaults: {},
  },
]

export const catalogMap = new Map(CATALOG.map((p) => [p.id, p]))
